###Get All Employee
GET http://localhost:3000/employee

###Post new employee
POST http://localhost:3000/employee

###Get a single employee
GET http://localhost:3000/employee/id

###Patch a single employee
PATCH http://localhost:3000/employee/id

###Delete a single employee
DELETE http://localhost:3000/employee